name: food_delivery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_auth: 
  firebase:
  cloud_firestore:
  google_sign_in : 
  flutter_masked_text: 
  firebase_storage:
  font_awesome_flutter: 
  image_picker:
  firebase_database: 
  geolocator: ^5.1.3
  google_maps_flutter:
  location: ^4.1.1
  permission_handler:
  android_intent: 
  awesome_dialog: ^2.0.0
  geocoding: 
  scoped_model: "1.1.0"
  carousel_slider: "3.0.0"
  cupertino_icons: ^0.1.2
  flutter_bloc:
  provider: 
  flutter_image_compress: "0.7.0"


dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_pattern:
  rxdart: 


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    -  assets/11.png
    -  assets/2.png
    -  assets/3.png
    -  assets/google.png
    -  assets/map.png
    -  assets/moto.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: free
      fonts:
        - asset: assets/fonts/freestyle.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true